### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by FGRibreau** [neomantra/redis-mod_luajit#1]
Awesome work @neomantra!

Even if it's still experimental, redis-mod-luajit will be shared in our next [RedisWeekly](http://redisweekly.com)!

**Comment by neomantra** [comment]
Thanks.  I did the initial work to free the idea from my brain and prove it could be done.  The API wrapping is complete except for vararg (e.g. HashSet). But, what is clear is that writing modules in C and writing modules in LuaJIT are both pretty straight forward.
